Repository OSGeo/grass-website, pull requests merged in 2024-07, with the labels that each got.

#442 Development: add URL to "Compile and install" under Quick links
  themes/grass/layouts/contribute/devel.html
Labels: enhancement

#444 News: GRASS GIS 8.4.0 released
  content/about/history/releases.md
  content/news/2024_07_27_GRASS_GIS_8_4_0_released.md
  data/grass.json
  static/images/news/grass840_gui_multiple_map_displays_and_history.png
Labels: news

#446 Fix markdown syntax typos
  content/news/2023_12_19_annual_report.md
Labels: bug

#447 GRASS 8.4.0 news: update Ubuntu link + add Nix
  content/news/2024_07_27_GRASS_GIS_8_4_0_released.md
Labels: enhancement
